debug: true
address: 127.0.0.1
timeout: 2
host: localhost
port: 8000
user: root
pass: admin
name: invoicein
secret: 213em718ink841
expired: 72
# {
#     "debug": true,
#     "server": {
#         "address": "127.0.0.1"
#     },
#     "context": {
#         "timeout": 2
#     },
#     "database": {
#         "host": "localhost",
#         "port": "8000",
#         "user": "root",
#         "pass": "admin",
#         "name": "invoicein"
#     },
#     "jwt": {
#         "secret": "213em718ink841",
#         "expired": 72
#     }
# }
