name: zip Repository
on: 
  push:
    branches:
      - "master"
      - "update_docker"
      - "staging"
jobs:
  zip-file:
    name: "Zip file"
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v4.1.7
      - name: zipping file
        run: |
          cd ../../
          ls -la
          zip -r Invoice.id-BE/result.zip Invoice.id-BE -x ".git/*" ".github/*" 
      - uses: actions/upload-artifact@v4.3.6
        with:
          name: my-artifact
          path: ${{ github.workspace }}/result.zip 
