name: Zip Files
on:
  push:
      branches:
      - "master"

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1.2
        with:
          files: /
          dest: result.zip
      - uses: actions/upload-artifact@v3.0
        with:
          name: my-artifact
          path: ${{ github.workspace }}/result.zip
