stages:
  - archieve

archieve:
  stage: archieve
  only: 
    - master
  image: ubuntu:18.04
  when:
    on_success
  before_script:
    - apt-get update
    - apt-get install zip -y
  script:
     - cd ~/
     - rm $PROJECT_NAME.zip
     - zip -r $PROJECT_NAME.zip $PROJECT_NAME -x ".git/*" ".github/*" 
